# Generated by Django 3.1.7 on 2021-04-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, default='', max_length=100)),
                ('local_number', models.IntegerField(blank=True, default=0)),
                ('postal_code', models.CharField(blank=True, default='', max_length=30)),
                ('city', models.CharField(blank=True, default='', max_length=50)),
                ('country', models.CharField(blank=True, default='', max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, default=0.0, max_digits=14)),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, default=0.0, max_digits=14)),
            ],
        ),
    ]
