# Generated by Django 3.1.7 on 2021-04-02 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=2000)),
                ('photo_url', models.CharField(blank=True, max_length=300)),
                ('preferred_time', models.CharField(blank=True, max_length=100)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=9)),
                ('create_date', models.DateField()),
                ('pickup_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address')),
            ],
        ),
    ]
