# Generated by Django 3.1.7 on 2021-04-02 16:48

from django.db import migrations
from ..models import Status, Unit


def add_statuses(apps, schema_editor):
    statuses = 'Available', 'Accepted', 'Rejected', 'Received'

    for status in statuses:
        Status.objects.create(name=status)


def add_units(apps, schema_editor):
    units = 'kg', 'l', 'piece(s)'

    for unit in units:
        Unit.objects.create(name=unit)


class Migration(migrations.Migration):
    dependencies = [
        ('donations', '0002_auto_20210402_1647')
    ]

    operations = [
        migrations.RunPython(add_statuses),
        migrations.RunPython(add_units),
    ]
